export const products = [
    {_id:1,
    name:'Conion Rice Cooker BE 28B60',
    image:'/images/rice-cook-1.jpg',
    description:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book",
    brand:'Canon',
    price:2080,
    countInStrock:5,
    rating:1.5,
    numReviews:4},
    {_id:2,
    name:'Philips Rice Cooker HD3027',
    image:'/images/rice-cook-2.jpg',
    description:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book",
    brand:'Philips',
    price:6080,
    countInStrock:6,
    rating:3.5,
    numReviews:4},
    {_id:3,
    name:'Walton Rice Cooker WRC-CGA22D',
    image:'/images/rice-cook-3.jpg',
    description:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book",
    brand:'Walton',
    price:3080,
    countInStrock:3,
    rating:5,
    numReviews:8},
    {_id:4,
    name:'Walton Rice Cooker WRC-P105 1.0 L',
    image:'/images/rice-cook-4.jpg',
    description:"Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book",
    brand:'Walton',
    price:1880,
    countInStrock:19,
    rating:2.5,
    numReviews:22}
];